site_name: nootnoot
site_description: Mutation testing for Python 3
site_url: https://nootnoot.readthedocs.io/
repo_url: https://github.com/boxed/nootnoot
repo_name: boxed/nootnoot
docs_dir: docs
nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Contributing: CONTRIBUTING.md
  - Changelog: HISTORY.md
  - Authors: AUTHORS.md
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - .
